// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDSbUMvSauHFL_RSK8imO5bza5rxQRO8',
    appId: '1:1007130425167:web:5cdd517cc0d1ddd6b1373a',
    messagingSenderId: '1007130425167',
    projectId: 'expense-tracker-22bdc',
    authDomain: 'expense-tracker-22bdc.firebaseapp.com',
    storageBucket: 'expense-tracker-22bdc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMI7kGkIwZ5c7R-Xe92bzS33Vehs4lid0',
    appId: '1:1007130425167:android:1d2d805ccf67f8c7b1373a',
    messagingSenderId: '1007130425167',
    projectId: 'expense-tracker-22bdc',
    storageBucket: 'expense-tracker-22bdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcpcKbZeTjiDM1oAlMLf0mdLpzZjot7aI',
    appId: '1:1007130425167:ios:0a9050aad0abaf2eb1373a',
    messagingSenderId: '1007130425167',
    projectId: 'expense-tracker-22bdc',
    storageBucket: 'expense-tracker-22bdc.firebasestorage.app',
    iosBundleId: 'com.expenseTracker.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdkCjwkSxev7DNTrgDaqAvL2J4kWqpnjU',
    appId: '1:1007130425167:ios:0e49e84aa66359a3b1373a',
    messagingSenderId: '1007130425167',
    projectId: 'expense-tracker-22bdc',
    storageBucket: 'expense-tracker-22bdc.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0vbxmLQqWNqaq-dIzP4AnsKLntDXzWr0',
    appId: '1:1007130425167:web:eb6c0a924b39fabcb1373a',
    messagingSenderId: '1007130425167',
    projectId: 'expense-tracker-22bdc',
    authDomain: 'expense-tracker-22bdc.firebaseapp.com',
    storageBucket: 'expense-tracker-22bdc.firebasestorage.app',
  );

}